# Handling Missing Data

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [6]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [7]:
float_data = pd.Series([1, 2, None], dtype='float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [8]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

## Filtering out missing data

In [9]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                    [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [13]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data[4] = np.nan

In [15]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [16]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [2]:
df = pd.DataFrame(np.random.standard_normal((7,3)))
df

0         1         2
0 -0.913548  0.157136 -0.928877
1 -0.108274 -1.288615  1.033083
2  0.016420 -0.854252 -1.550188
3  0.161443 -1.254650 -0.332543
4  2.516855 -0.589453  0.179183
5 -0.199678 -0.105659  0.031207
6  0.079476  1.512657 -1.672334

In [3]:
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan

In [4]:
df

0         1         2
0 -0.913548       NaN       NaN
1 -0.108274       NaN       NaN
2  0.016420       NaN -1.550188
3  0.161443       NaN -0.332543
4  2.516855 -0.589453  0.179183
5 -0.199678 -0.105659  0.031207
6  0.079476  1.512657 -1.672334

In [5]:
df.dropna()

0         1         2
4  2.516855 -0.589453  0.179183
5 -0.199678 -0.105659  0.031207
6  0.079476  1.512657 -1.672334

In [6]:
df.dropna(thresh=2)

0         1         2
2  0.016420       NaN -1.550188
3  0.161443       NaN -0.332543
4  2.516855 -0.589453  0.179183
5 -0.199678 -0.105659  0.031207
6  0.079476  1.512657 -1.672334

## Filling in Missing Data

In [7]:
df.fillna(0)

0         1         2
0 -0.913548  0.000000  0.000000
1 -0.108274  0.000000  0.000000
2  0.016420  0.000000 -1.550188
3  0.161443  0.000000 -0.332543
4  2.516855 -0.589453  0.179183
5 -0.199678 -0.105659  0.031207
6  0.079476  1.512657 -1.672334

In [8]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.913548  0.500000  0.000000
1 -0.108274  0.500000  0.000000
2  0.016420  0.500000 -1.550188
3  0.161443  0.500000 -0.332543
4  2.516855 -0.589453  0.179183
5 -0.199678 -0.105659  0.031207
6  0.079476  1.512657 -1.672334

In [9]:
df = pd.DataFrame(np.random.standard_normal((6,3)))

In [10]:
df.iloc[2:, 1] = np.nan

In [11]:
df.iloc[4: , 2] = np.nan

In [12]:
df

0         1         2
0 -1.616975  0.311380  1.670204
1 -1.401837 -0.204675 -0.062169
2 -0.525637       NaN  0.076964
3 -0.582743       NaN -0.149714
4 -0.371901       NaN       NaN
5 -2.094818       NaN       NaN

In [13]:
df.fillna(method="ffill")

0         1         2
0 -1.616975  0.311380  1.670204
1 -1.401837 -0.204675 -0.062169
2 -0.525637 -0.204675  0.076964
3 -0.582743 -0.204675 -0.149714
4 -0.371901 -0.204675 -0.149714
5 -2.094818 -0.204675 -0.149714

In [14]:
df.fillna(method="ffill", limit=2)

0         1         2
0 -1.616975  0.311380  1.670204
1 -1.401837 -0.204675 -0.062169
2 -0.525637 -0.204675  0.076964
3 -0.582743 -0.204675 -0.149714
4 -0.371901       NaN -0.149714
5 -2.094818       NaN -0.149714

In [15]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [16]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# Data Transformation

## Removing Duplicates

In [18]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                    "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [19]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [21]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [22]:
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [23]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [24]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## Transforming Data Using function ormapping

In [26]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", 
                              "pastrami", "corned beef", "bacon", "pastrami", "honey ham", "nova lox"],
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [28]:
meat_to_animal={
    "bacon": "pig",
    "pulled pork": "ping",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "ping",
    "nova lox": "salmon"
    
}
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'ping',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'ping',
 'nova lox': 'salmon'}

In [29]:
data["animal"] = data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0    ping
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0    ping
8     nova lox     6.0  salmon

In [30]:
def get_animal(x):
    return meat_to_animal[x]

data["food"].map(get_animal)

0       pig
1      ping
2       pig
3       cow
4       cow
5       pig
6       cow
7      ping
8    salmon
Name: food, dtype: object

## Replacing values

In [31]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [32]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [33]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [34]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [35]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## Renaning Axis Indexes

In [2]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                   index=["Ohio", "Colorado", "New York"],
                   columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [3]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [4]:
data.index = data.index.map(transform)

In [5]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [6]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [7]:
data.rename(index={"OHIO": "INDIANA"},
           columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

## Descretization and Binning

In [8]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [10]:
bins = [18, 25, 35, 60, 100]

age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [11]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [12]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [13]:
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [14]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [15]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [16]:
data = np.random.uniform(size=20)
data

array([0.88729241, 0.8414837 , 0.31765633, 0.34295145, 0.430818  ,
       0.13174069, 0.23151679, 0.95538079, 0.16284571, 0.07963086,
       0.37919853, 0.69362969, 0.45673782, 0.58976957, 0.31541267,
       0.9026097 , 0.60054166, 0.786972  , 0.76989942, 0.58991791])

In [19]:
pd.cut(data, 4, precision=2)

[(0.74, 0.96], (0.74, 0.96], (0.3, 0.52], (0.3, 0.52], (0.3, 0.52], ..., (0.74, 0.96], (0.52, 0.74], (0.74, 0.96], (0.74, 0.96], (0.52, 0.74]]
Length: 20
Categories (4, interval[float64, right]): [(0.079, 0.3] < (0.3, 0.52] < (0.52, 0.74] < (0.74, 0.96]]

In [20]:
data = np.random.standard_normal(1000)

In [21]:
quartiles = pd.qcut(data, 4, precision=2)

In [22]:
quartiles

[(0.63, 2.72], (0.033, 0.63], (-3.4499999999999997, -0.68], (0.63, 2.72], (-3.4499999999999997, -0.68], ..., (-0.68, 0.033], (-3.4499999999999997, -0.68], (-3.4499999999999997, -0.68], (-3.4499999999999997, -0.68], (0.033, 0.63]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.4499999999999997, -0.68] < (-0.68, 0.033] < (0.033, 0.63] < (0.63, 2.72]]

In [23]:
pd.value_counts(quartiles)

(-3.4499999999999997, -0.68]    250
(-0.68, 0.033]                  250
(0.033, 0.63]                   250
(0.63, 2.72]                    250
dtype: int64

In [24]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1]).value_counts()

(-3.4379999999999997, -1.291]    100
(-1.291, 0.0329]                 400
(0.0329, 1.239]                  400
(1.239, 2.716]                   100
dtype: int64

## Detecting and Filtering Outliers

In [25]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.033879     0.025439     0.018767     0.003985
std       1.021666     1.004394     0.965938     1.012257
min      -3.493223    -4.170605    -3.148009    -3.252823
25%      -0.740372    -0.655461    -0.607055    -0.682313
50%      -0.041790     0.041590     0.029109     0.011475
75%       0.654806     0.679546     0.679963     0.634986
max       3.482049     3.286267     3.446304     3.400317

In [26]:
col = data[2]

In [27]:
col[col.abs() > 3]

277   -3.072860
699    3.446304
815    3.205553
999   -3.148009
Name: 2, dtype: float64

In [29]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
277  0.030836  1.945339 -3.072860  0.072169
281  0.448527  3.091602  0.467002 -0.014515
383  0.084387 -4.170605 -1.297919 -0.007514
420  3.482049 -0.210995 -1.074655  0.634878
663 -0.483393 -3.314301  0.066468  0.660573
689 -0.791111 -1.272192  1.392293  3.400317
698 -0.632173  3.286267  0.232549 -1.266057
699 -0.816273 -0.587879  3.446304  0.286163
790 -3.493223 -0.029374 -0.064427  0.023587
815  1.814630 -0.707927  3.205553 -1.672538
984 -0.974104  1.303415  0.002444 -3.252823
999 -0.332156 -0.143860 -3.148009 -0.975857

In [30]:
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.033868     0.026546     0.018336     0.003838
std       1.018562     0.997999     0.963089     1.010207
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.740372    -0.655461    -0.607055    -0.682313
50%      -0.041790     0.041590     0.029109     0.011475
75%       0.654806     0.679546     0.679963     0.634986
max       3.000000     3.000000     3.000000     3.000000

In [31]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1  1.0 -1.0  1.0  1.0
2  1.0  1.0 -1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0  1.0 -1.0

## Permutation and Random Sampling

In [32]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [34]:
sampler = np.random.permutation(5)
sampler

array([1, 3, 4, 0, 2])

In [35]:
df.take(sampler)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20

In [37]:
columns_sampler = np.random.permutation(7)
columns_sampler

array([5, 1, 2, 3, 0, 4, 6])

In [39]:
df.take(columns_sampler, axis="columns")

5   1   2   3   0   4   6
0   5   1   2   3   0   4   6
1  12   8   9  10   7  11  13
2  19  15  16  17  14  18  20
3  26  22  23  24  21  25  27
4  33  29  30  31  28  32  34

In [40]:
df.sample(n=3)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20

In [41]:
choices = pd.Series([5, 7, -1, 6, 4])

In [42]:
choices.sample(n=10, replace=True)

3    6
2   -1
3    6
4    4
4    4
3    6
2   -1
3    6
4    4
0    5
dtype: int64

## Computing Indicator/Dummy Variables

In [43]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                  "data1": range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [44]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [46]:
dummies = pd.get_dummies(df["key"], prefix="key")
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [47]:
mnames = ["movie_id", "title", "genres"]

movies = pd.read_table("datasets/movielens/movies.dat", sep="::",
                      header=None, names=mnames, engine="python")

In [48]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [50]:
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [51]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [52]:
np.random.seed(12345)
values = np.random.uniform(size=10)

In [53]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [54]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

# Extension Data Types

In [55]:
s = pd.Series([1, 2, 3, None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [56]:
s.dtype

dtype('float64')

In [58]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [59]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [61]:
s.dtype

Int64Dtype()

In [62]:
s[3]

<NA>

In [63]:
s[3] is pd.NA

True

In [64]:
s = pd.Series([1, 2, 3, None], dtype="Int64")
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [65]:
pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [66]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                  "B": ["one", "two", "three", None],
                  "C":[False, None, False, True]})
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [67]:
df["A"] = df["A"].astype("Int64")

In [68]:
df["B"] = df["B"].astype("string")

In [69]:
df["C"] = df["C"].astype("boolean")

In [70]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

# String Manipulation

## Python Built-In String Object Methods

In [71]:
val = "a, b, guido"
val.split(",")

['a', ' b', ' guido']

In [72]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [73]:
first, second, third = pieces

In [74]:
first + "::" + second + "::" + third

'a::b::guido'

In [75]:
"::".join(pieces)

'a::b::guido'

In [76]:
"guido" in val

True

In [78]:
val.index(",")

1

In [79]:
val.find(":")

-1

In [80]:
val.index(":")

ValueError: substring not found

In [81]:
val.count(",")

2

In [82]:
val.replace(",", "::")

'a:: b:: guido'

In [84]:
val.replace(",", "")

'a b guido'

## Regular Expressions

In [85]:
import re

In [86]:
text = "foo            bar \t   bar       \tqux"

In [87]:
re.split(r"\s+", text)

['foo', 'bar', 'bar', 'qux']

In [88]:
regex = re.compile(r"\s+")

In [89]:
regex.split(text)

['foo', 'bar', 'bar', 'qux']

In [90]:
regex.findall(text)

['            ', ' \t   ', '       \t']

In [92]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahll.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [93]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [94]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahll.com']

In [95]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [96]:
text[m.start():m.end()]

'dave@google.com'

In [97]:
print(regex.match(text))

None


In [100]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


## String function ins pandas

In [103]:
data = {"Datve": "dave@google.com", "Steve": "steve@gmail.com", 
        "Rob": "rob@gmail.com", "Ryan": "ryan@yahll.com", "Wes": np.nan}
data

{'Datve': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Ryan': 'ryan@yahll.com',
 'Wes': nan}

In [105]:
data = pd.Series(data)
data

Datve    dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Ryan      ryan@yahll.com
Wes                  NaN
dtype: object

In [106]:
data.isna()

Datve    False
Steve    False
Rob      False
Ryan     False
Wes       True
dtype: bool

In [107]:
data.str.contains("gmail")

Datve    False
Steve     True
Rob       True
Ryan     False
Wes        NaN
dtype: object

In [109]:
data_as_string_ext = data.astype('string')
data_as_string_ext

Datve    dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Ryan      ryan@yahll.com
Wes                 <NA>
dtype: string

In [110]:
data_as_string_ext.str.contains("gmail")

Datve    False
Steve     True
Rob       True
Ryan     False
Wes       <NA>
dtype: boolean

In [115]:
# r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
#pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags=re.IGNORECASE)

Datve    [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Ryan      [(ryan, yahll, com)]
Wes                        NaN
dtype: object

In [117]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [118]:
matches

Datve    (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Ryan      (ryan, yahll, com)
Wes                      NaN
dtype: object

In [119]:
matches.str.get(1)

Datve    google
Steve     gmail
Rob       gmail
Ryan      yahll
Wes         NaN
dtype: object

In [120]:
data.str[:5]

Datve    dave@
Steve    steve
Rob      rob@g
Ryan     ryan@
Wes        NaN
dtype: object

In [121]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Datve   dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Ryan    ryan   yahll  com
Wes      NaN     NaN  NaN

# Categorical Data

In [122]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [123]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [125]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [126]:
values = pd.Series([0, 1, 0, 0] * 2)
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [127]:
dim = pd.Series(['apple', 'orange'])

In [128]:
dim

0     apple
1    orange
dtype: object

In [129]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

## Categorical Extension Type in Pandas

In [2]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)

df = pd.DataFrame({'fruit': fruits,
                  'basket_id' : np.arange(N),
                  'count': rng.integers(3, 15, size=N),
                  'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [3]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [5]:
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [7]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [8]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [9]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [10]:
df['fruit'] = df['fruit'].astype('category')
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [11]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [12]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]

my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [13]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [14]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

## Computation with Categoricals

In [16]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)

draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [18]:
bins = pd.qcut(draws, 4)

In [19]:
bins   

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [20]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [21]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [23]:
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws)
          .groupby(bins)
          .agg(['count', 'min', 'max'])
          .reset_index())

results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [25]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [26]:
N = 10_000_000

labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N// 4))

categories = labels.astype('category')

In [27]:
labels.memory_usage(deep=True)

600000132

In [28]:
categories.memory_usage(deep=True)

10000544

In [29]:
%time _ = labels.astype('category')

CPU times: total: 359 ms
Wall time: 352 ms


In [30]:
%timeit labels.value_counts()

243 ms ± 11.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [32]:
%timeit categories.value_counts()

35.7 ms ± 491 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Categorical Methods

In [33]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [34]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [35]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [36]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [37]:
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [38]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [39]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In [40]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [41]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [44]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [45]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [46]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1