In [1]:
import numpy as np

In [3]:
data = np.array([[[[1,3,4]]]])
data

array([[[[1, 3, 4]]]])

In [4]:
data.ndim

4

In [9]:
np.array(data, ndmin=5)

array([[[[[1, 3, 4]]]]])

In [10]:
data.ndim

4

In [8]:
np.array(data, ndim=data.ndim + 1)

TypeError: array() got an unexpected keyword argument 'ndim'

In [11]:
Array1 = np.array([[1, 2, 3], [4, 5, 6]]) 
Array2 = np.array([[2, 3],[3, 2]])
np.dot(Array1, Array2)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [12]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])
array

array([ 10,   3,   1, 203, 404, 204,  20, 302,  30, 402, 192])

In [16]:
array[::-1]

array([192, 402,  30, 302,  20, 204, 404, 203,   1,   3,  10])

In [18]:
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]  
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [19]:
a = np.arange(3*4*5*6).reshape((3,4,5,6)) 
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3)) 
np.dot(a, b)[2,3,2,1,2,2]

499128

In [21]:
a = np.array([3, 7, 32], dtype = complex) 
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [22]:
np.random.seed(100) 
a = np.random.uniform(1,50, 20)
a

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [23]:
np.where(a < 10, 10, np.where(a > 30, 30, a))

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [27]:
array1 = np.array([[1,2],[3,4]]) 

array1

array([[1, 2],
       [3, 4]])

In [28]:
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
array2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
np.vstack((array1, array2))

array([[ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [33]:
 array = np.array([10,3,1,203,404,204,20,302,30,402,192]) 
array

array([ 10,   3,   1, 203, 404, 204,  20, 302,  30, 402, 192])

In [36]:
np.insert(array, 4, [1, 2, 3, 4])

array([ 10,   3,   1, 203,   1,   2,   3,   4, 404, 204,  20, 302,  30,
       402, 192])

In [41]:
np.full((3,3), 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [44]:
def bub_sort(array): 
    for i in range(0, len(array)): 
        for j in range(0, len(array) - i - 1): 
            if array[j] < array[j + 1]: 
                temp = array[j] 
                array[j] = array[j + 1] 
                array[j+1] = temp 
    return array 

my_array = np.array([20,14,25,16,45,60,12,9])
bub_sort(my_array)

array([60, 45, 25, 20, 16, 14, 12,  9])

In [52]:
a = np.array((2, 5))
a

TypeError: Cannot interpret '5' as a data type

In [49]:
a.shape

(2,)

In [58]:
np.arange(5, 2)

array([], dtype=int32)

In [60]:
Sample = np.array([[1,2],[3,4],[5,6],[7,8]])
Sample.shape

(4, 2)

In [61]:
Sample.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [64]:
arr[[0:3], [1]]

SyntaxError: invalid syntax (4237372047.py, line 1)

In [65]:
arr[0:3][1]

array([4, 5, 6])

In [66]:
arr[0:3, 1]

array([2, 5, 8])

In [67]:
arr1 = np.arange(20,2) 
arr1

array([], dtype=int32)

In [68]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
np.hstack((arr1, arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
array1 = np.array([[1,2],[3,4]]) 
array2 = np.array([[5,6],[7,8]])

In [72]:
np.vstack((array1, array2))

array([[ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [76]:
a = np.array([4,12,29]) 
b = np.array([13,21,4])

In [77]:
np.cross(a, b)

array([-561,  361,  -72])

In [78]:
a = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25]) 
b = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])
np.corrcoef(a, b)

array([[1., 1.],
       [1., 1.]])

In [80]:
 sample = {1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}

In [81]:
np.array(sample)

array({1: [1, 2], 2: [[1], [2]], 3: [[1, 2], [3, 4], [4, 5]], 4: [1], 5: [1, 2, 3, 4, 5]},
      dtype=object)

In [82]:
arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])
arr1

array([[3, 2, 1],
       [6, 4, 5],
       [8, 7, 9]])

In [86]:
array.min(axis=0)

1